apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: podwatcher
  labels:
    app: podwatcher
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/log
  - pods/status
  verbs:
  - get
  - list
  - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: podwatcher
  name: podwatcher
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: podwatcher
  name: podwatcher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: podwatcher
subjects:
- kind: ServiceAccount
  name: podwatcher
  namespace: kube-system
